apps/nanjing/urls.py
from django.conf.urls import patterns, include, url 

import views

urlpatterns = patterns('',
    url(r'^(\w+)/articles-list/(\d+)/$', views.articles_list, name='articles_list'),
    url(r'^(\w+)/article-detail/(\d+)/$', views.article_detail, name='article_detail'),
    url(r'^(\w+)/open-account/$', views.open_account, name='open_account'),
    url(r'^(\w+)/sim-account/$', views.sim_account, name='sim_account'),
    url(r'^(\w+)/activity-user/(\d+)/$', views.activity_user, name='activity_user'),
    url(r'^(\w+)/commit-success/$', views.commit_success, name='commit_success'),
    url(r'^(\w+)/activity-list/$', views.activity_list, name='activity_list'),
    url(r'^(\w+)/show_question/$', views.show_question, name='show_question'),
)

blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url 

import myadmin

urlpatterns = patterns('',
    url(r'^$', myadmin.news_list, name='news_list'),
    url(r'^category-list/$', myadmin.category_list, name='category_list'),
    url(r'^news-add/$', myadmin.news_add, name='news_add'),  #news意义已失效，但仍有。此处是添加,修改文章
    url(r'^article-detail/(\d+)/$', myadmin.article_detail, name='article_detail'),
    url(r'^articles-list/$', myadmin.articles_list, name='articles_list'),
    #url(r'^article-update/$', myadmin.article_update, name='article_update'),
    url(r'^article-delete/(\d+)/$', myadmin.article_delete, name='article_delete'),
    url(r'^login/$', myadmin.mylogin, name='login'),
    url(r'^logout/$', myadmin.mylogout, name='logout'),

    url(r'^reply/$', myadmin.reply, name='reply'),  #关注回复，无匹配回复, 关键字编辑
    url(r'^message-update/$', myadmin.message_update, name='message_update'),  #message的所有修改
    url(r'^keyword-reply/$', myadmin.keyword_reply, name='keyword_reply'),
    url(r'^users-list/$', myadmin.users_list, name='users_list'),
    url(r'^groups-list/$', myadmin.groups_list, name='groups_list'),
    url(r'^groups-delete/$', myadmin.groups_delete, name='groups_delete'),
    url(r'^group-name-update/$', myadmin.group_name_update, name='group_name_update'),
    url(r'^category-delete/$', myadmin.category_delete, name='category_delete'),
    url(r'^category-name-update/$', myadmin.category_name_update, name='category_name_update'),
    url(r'^category-add/$', myadmin.category_add, name='category_add'),
    url(r'^category-remove/$', myadmin.category_remove, name='category_remove'),

    url(r'^menus-list/$', myadmin.menus_list, name='menus_list'),
    url(r'^send-create-menu/$', myadmin.send_create_menu, name='send_create_menu'),
    url(r'^menu-add/$', myadmin.menu_add, name='menu_add'),
    url(r'^menu-update/$', myadmin.menu_update, name='menu_update'),
    url(r'^menu-click/$', myadmin.menu_click, name='menu_click'),
    url(r'^menu-url/$', myadmin.menu_url, name='menu_url'),
    url(r'^menu-delete/$', myadmin.menu_delete, name='menu_delete'),
    url(r'^menu-change-name/$', myadmin.menu_change_name, name='menu_change_name'),
    url(r'^sub-menu-update/$', myadmin.sub_menu_update, name='sub_menu_update'),
    url(r'^sub-menu-add/$', myadmin.sub_menu_add, name='sub_menu_add'),

    url(r'^text-update/$', myadmin.text_update, name='text_update'),
    url(r'^news-update/$', myadmin.news_update, name='news_update'),
   # url(r'^keyword-update/(\d+)/$', myadmin.keyword_update, name='keyword_update'),
    url(r'^keyword-add/$', myadmin.keyword_add, name='keyword_add'),
    url(r'^keyword-delete/$', myadmin.keyword_delete, name='keyword_delete'),
    url(r'^groups-add/$', myadmin.groups_add, name='groups_add'),
    url(r'^group-update/$', myadmin.group_update, name='group_update'),
    url(r'^group-remove/$', myadmin.group_remove, name='group_remove'),

    url(r'^activity-list/$', myadmin.activity_list, name='activity_list'),
    url(r'^open-account-list/$', myadmin.open_account_list, name='open_account_list'),
    url(r'^sim-account-list/$', myadmin.sim_account_list, name='sim_account_list'),


    url(r'^account-delete/(\w+)/(\d+)/$', myadmin.account_delete, name='account_delete'),
    url(r'^activity-add/$', myadmin.activity_add, name='activity_add'),
    url(r'^activity-delete/(\d+)/$', myadmin.activity_delete, name='activity_delete'),
    url(r'^activity-account-list/(\d+)/$', myadmin.activity_account_list, name='activity_account_list'),
    url(r'^activity-status/(\d+)/$', myadmin.activity_status, name='activity_status'),


    url(r'^questions-list/$', myadmin.questions_list, name='questions_list'),  #客服列表
    url(r'^answer-question/$', myadmin.answer_question, name='answer_question'),  #客服列表
    url(r'^kefu-delete/$', myadmin.kefu_delete, name='kefu_delete'),  #客服列表

)

yimi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from yimi.settings import TOKEN
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^%s/(\d+)/$'%TOKEN, 'blog.views.weixin_api', name='weixin_api'),
    url(r'^$', 'blog.views.message', name='message'),
    url(r'^yimi-admin/', include('blog.urls', namespace="yimi_admin")),
    url(r'^a/', include('apps.nanjing.urls', namespace="nanjing")), #appitem slug

    url(r'^myueditor/upload/$', 'myueditor.views.upload', name='upload'),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
#coding:utf8

#import pytz
import time
import datetime
import urllib2
import os

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, m2m_changed
from django.core.cache import cache
from utils import upload_file_handler, method_get_api, method_post_api
from yimi.settings import TIME_ZONE, TOKEN_CACHE_PRE, TOKEN

TYPE_LIST = (
    ('text', '文本回复'),
    ('news', '图文回复'),
    ('event', 'event'),
)
RE_TYPE_LIST = (
    ('text', '文本回复'),
    ('news', '图文回复'),
)

MESSAGE_TAG = (
    ('keyword_recontent', '关键字回复'),
    ('keyword_default_recontent', '无匹配回复'),
    ('subscribe', '关注'),
   # ('unsubscribe', '取消订阅')
)

MENU_BUTTON_CHOICES = (
    ('click', '关键字回复'),
    ('view', '跳转'),
    ('sub_button', '子按键'),
)

SUB_BUTTON_CHOICES = (
    ('click', '单击动作'),
    ('view', '跳转'),
)

class Message(models.Model):
    type = models.CharField(max_length=100, blank=True, null=True, verbose_name='收到信息类型', choices=TYPE_LIST)
    keyword = models.CharField(max_length=100, blank=True, null=True, verbose_name='关键字')
    tag = models.CharField(max_length=100, default='keyword_recontent',verbose_name='标示', choices=MESSAGE_TAG)
    retype = models.CharField(max_length=100, verbose_name='返回信息类型', default='text',choices=RE_TYPE_LIST)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    class Meta:
        ordering = ['-id']
    def __unicode__(self):
        return '%s__%s' % (self.keyword or 'default', self.tag)

    def get_resource(self):
        if self.retype == 'text':
            return self.text_set.first()        
        elif self.retype == 'news':
            return self.news_set.first()
    def get_create_time(self):
     #   c_time = self.create_time
     #   to_zone = pytz.timezone(TIME_ZONE)
     #   local = c_time.astimezone(to_zone)
     #   return local.strftime("%Y%m%d%H%M")
        time_stamp=time.mktime(self.create_time.timetuple())
        return long(time_stamp)

class Text(models.Model):
    message = models.ForeignKey('Message', on_delete=models.SET_NULL, blank=True, null=True, verbose_name="信息")
    content = models.TextField(blank=True, null=True, verbose_name='内容')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __unicode__(self):
        return self.content


class News(models.Model):
    messages = models.ManyToManyField('Message', blank=True, null=True, verbose_name="信息")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    articles = models.ManyToManyField('Article', blank=True, null=True, verbose_name='素材') 
    order_dic = models.CharField(max_length=512, blank=True, null=True, verbose_name='素材顺序') #"{art1.id:1, art2.id:2}"
    
    class Meta:
        ordering = ['-id']



class Article(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True, verbose_name='标题')
    author = models.CharField(max_length=100, blank=True, null=True, verbose_name='作者')
    description = models.TextField(blank=True, null=True, verbose_name='描述')
    picurl = models.CharField(max_length=500, blank=True, null=True, verbose_name='图片链接')
    url = models.CharField(max_length=500, blank=True, null=True, verbose_name='原文链接')
    image = models.FileField(
        max_length=128, blank=True, null=True, upload_to=upload_file_handler, verbose_name="本地上传")
    content = models.TextField(blank=True, null=True, verbose_name='正文')
    create_time = models.DateTimeField(auto_now_add=True,  blank=True, null=True,verbose_name='创建时间')
    class Meta:
        verbose_name_plural = '素材'
        verbose_name = '素材'
        ordering = ['-id']

    def __unicode__(self):
        return self.title
    def get_appitem(self):
            return self.appitem_set.first()

    def get_image_url(self):
        if self.picurl:
            return self.picurl
        elif self.image:
            appitem = self.get_appitem()
            domain = appitem.domain
            url_prefix = 'http://%s/media/' % domain
            return url_prefix + self.image.name
        else:
            return '/'
    
    def get_url(self):
        appitem = self.get_appitem()

        return 'http://%s/a/%s/article-detail/%s/' % (appitem.domain, appitem.slug, self.id)

    def get_description(self):
        if self.description:
            return self.description
        else:
            return self.content[:15]

    def get_category(self):
        return self.category_set.first()

class Category(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='名称')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    articles = models.ManyToManyField('Article', blank=True, null=True, verbose_name='素材') 
    status = models.BooleanField(default=True, verbose_name="是否显示")
    class Meta:
        ordering = ['-id']
    def __unicode__(self):
        return self.name
    
    def get_url(self):
        appitem = self.appitem_set.first()
        user_info_url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid='+appitem.appid+'&redirect_uri=%s&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect'
        url = 'http://%s/a/%s/articles-list/%s/' % (appitem.domain, appitem.slug, self.id)
        return user_info_url % url
        return url

#SUBSCRIBE_STATUS_CHOICES = (
#    (0, '未关注'),
#    (1, '关注'),
#)

class AppUser(models.Model):
   # subscribe = models.IntegerField(max_length=2, verbose_name="是否关注", blank=True, null=True, choices=SUBSCRIBE_STATUS_CHOICES)
    openid = models.CharField(max_length=128, blank=True, null=True, verbose_name='用户标识')
    nickname = models.CharField(max_length=128, blank=True, null=True, verbose_name='昵称')
    sex = models.IntegerField(max_length=2, verbose_name="性别", blank=True, null=True)
    city = models.CharField(max_length=128, blank=True, null=True, verbose_name='城市')
    province = models.CharField(max_length=128, blank=True, null=True, verbose_name='省份')
    country = models.CharField(max_length=128, blank=True, null=True, verbose_name='国家')
    language = models.CharField(max_length=128, blank=True, null=True, verbose_name='用户语言')
    headimgurl = models.CharField(max_length=500, blank=True, null=True, verbose_name='头像')
   # subscribe_time = models.CharField(max_length=20, blank=True, null=True, verbose_name='用户关注的时间')

    def __unicode__(self):
        return self.nickname

class AppGroup(models.Model):
    groupid = models.CharField(max_length=128, blank=True, null=True, verbose_name='组id')
    name = models.CharField(max_length=128, blank=True, null=True, verbose_name='组名称')
    count = models.IntegerField(verbose_name="组内用户数量", default=0)
    app_users = models.ManyToManyField('AppUser', blank=True, null=True, verbose_name='组成员') 
    status = models.BooleanField(default=False, verbose_name="是否白名单组（可看到未显示的文章分类）")

class AppItem(models.Model):
    user = models.ForeignKey(User, verbose_name='用户', blank=True, null=True)
    name = models.CharField(max_length=128, blank=True, null=True, verbose_name='名称')
    slug = models.CharField(max_length=128, blank=True, null=True, verbose_name='app名称,唯一' )
    domain = models.CharField(max_length=128, blank=True, null=True, verbose_name='全域名(不包含http://)')
    appid = models.CharField(max_length=128, blank=True, null=True, verbose_name='APPID')
    app_secret = models.CharField(max_length=128, blank=True, null=True, verbose_name='APP_SECRET')
    token_cache_key = models.CharField(max_length=128, default='yimi_access_token', blank=True, null=True, verbose_name='缓存token的key')
    app_groups = models.ManyToManyField('AppGroup', blank=True, null=True, verbose_name='app内的组') 
    app_users = models.ManyToManyField('AppUser', blank=True, null=True, verbose_name='app内用户') 
    menu_buttons = models.ManyToManyField('MenuButton', blank=True, null=True, verbose_name='app内的button') 
    messages = models.ManyToManyField('Message', blank=True, null=True, verbose_name='app内的处理事件') 
    qrcodes = models.ManyToManyField('QRCode', blank=True, null=True, verbose_name='app内的二维码') 
    categories = models.ManyToManyField('Category', blank=True, null=True, verbose_name='分类') 
    articles = models.ManyToManyField('Article', blank=True, null=True, verbose_name='元素材') 
    news = models.ManyToManyField('News', blank=True, null=True, verbose_name='图文素材') 
    is_valid = models.BooleanField(default=False, verbose_name="是否验证")
    def __unicode__(self):
        return self.name or self.appid

    def get_weixin_api(self):
        return 'http://%s/%s/%s/' % (self.domain, TOKEN, self.id)
        
    def successed(self, data):
        if data.get('errcode') == 0 and data.get('errmsg') == 'ok':
            return True
        else:
            return False

    def get_token(self):
        token_cache_key = TOKEN_CACHE_PRE+'__'+self.appid #对不同的app指定不同的缓存
        token = cache.get(token_cache_key)
        if token:
            return token
        else:
            url = 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s' % (self.appid, self.app_secret)
            dict_data = method_get_api(url)
            token = dict_data.get('access_token')
            expires_in = dict_data.get('expires_in')
            if token and expires_in:
                cache.set(token_cache_key, token, expires_in-60)
            return token or ''
    
    def get_all_user(self, next_id=None):
        '''得到所有用户列表''' 
        suffix = ''
        if next_id:
            suffix = '&next_openid=' + next_id
        return method_get_api('https://api.weixin.qq.com/cgi-bin/user/get?access_token='+self.get_token()+suffix)
    
    def get_user_info(self, openid):
        '''得到用户的详细信息''' 
        url = 'https://api.weixin.qq.com/cgi-bin/user/info?access_token=%s&openid=%s&lang=zh_CN' % (self.get_token(), openid)
        return method_get_api(url)
    
    
    def create_menu(self, post_data):
        '''创建菜单，成功返回True'''

templates/yimi_admin/article_detail.html
{% extends "yimi_admin/base.html" %}
{% block right_div %}
<div>

<h1>{{article.title}}</h1>
<p>{{article.content}}</p>

</div>

{% endblock %}

templates/yimi_admin/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
<title>亿米传媒 业务管理后台</title>
<link href="/static/myadmin/css/main.css" rel="stylesheet" type="text/css" />
<link href="/static/myadmin/css/mainstyle.css" rel="stylesheet" type="text/css" />


 <!--<link href="/static/bootstrap/assets/css/bootstrap.css" rel="stylesheet" type="text/css" /> -->
<link href="/static/myadmin/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
<!--[if IE 8]><link href="/static/watch/css/ie8.css" rel="stylesheet" type="text/css" /><![endif]-->
<!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'> -->

<script src="http://libs.baidu.com/jquery/1.8.2/jquery.js"></script>
<script src="http://libs.baidu.com/jqueryui/1.9.1/jquery-ui.min.js "></script>



<script type="text/javascript" src="/static/watch/js/plugins/forms/jquery.form.wizard.js"></script>
<script type="text/javascript" src="/static/watch/js/plugins/forms/jquery.form.js"></script>
<script type="text/javascript" src="/static/watch/js/plugins/tables/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="/static/myadmin/js/functions.js"></script>

<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.js"></script>
<script type="text/javascript" src="/static/ueditor/lang/zh-cn/zh-cn.js"></script>

</head>

<body >
    <div id="top">
        <div class="fixed">
        <div class="container">
            <a href="" title="" class="logo">亿米传媒 业务管理后台</a>
            <ul class="top-menu">
                <li class="dropdown">
                    <a class="user-menu" data-toggle="dropdown"><span>{{request.user.username}} <b class="caret"></b></span></a>
                    <a href="{% url 'yimi_admin:logout' %}" title=""id="sh_logout" class="user-menu" style="display:none;"><span>&nbsp;退出</span></a>
                </li>

            </ul>
        </div>
    </div>
    </div>

    <!-- Content container -->
    <div id="container" class="container row-fluid">

        <!-- Sidebar -->
        <div id="sidebar" class="span2">
            <div class="sidebar-tabs">
                <div id="general">
                    <!-- Main navigation -->
                    <ul class="navigation widget">
                        <li><a href="#" title="" class="expand subOpened"><i class="icon-reorder"></i>{{appitem.name}}<strong></strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:news_list' %}">文章管理</a></li>
                                <li><a href="{% url 'yimi_admin:news_add' %}">增加文章</a></li>
                                <li><a href="{% url 'yimi_admin:category_list' %}">分类管理</a></li>
                                <li><a href="{% url 'yimi_admin:articles_list' %}">文章分类管理</a></li>
                            </ul>
                        </li>
                         <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>自动回复<strong>2</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:reply' %}?tag=subscribe">关注回复</a></li>
                                <li><a href="{% url 'yimi_admin:reply' %}?tag=keyword_default_recontent">无匹配回复</a></li>
                                <li><a href="{% url 'yimi_admin:keyword_reply' %}">关键字回复</a></li>
                            </ul>
                        </li>
                         <li><a href="{% url 'yimi_admin:users_list' %}" title="" class="expand"><i class="icon-reorder"></i>用户管理<strong>1</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:users_list' %}">用户管理</a></li>
                                <li><a href="{% url 'yimi_admin:groups_list' %}">组管理</a></li>
                            </ul>
                        </li>                        
                        <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>自定义菜单<strong>2</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:menus_list' %}">菜单管理</a></li>
                                <li><a href="{% url 'yimi_admin:menu_add' %}">增加一级菜单</a></li>
                            </ul>
                        </li>                                                                       
                        <li><a href="#" title="" class="expand"><i class="icon-reorder"></i>用户提交信息管理<strong>3</strong></a>
                            <ul>
                                <li><a href="{% url 'yimi_admin:activity_list' %}">活动管理</a></li>
                                <li><a href="{% url 'yimi_admin:sim_account_list' %}">预约开户</a></li>
                                <li><a href="{% url 'yimi_admin:open_account_list' %}">申请模拟账户</a></li>
                                <li><a href="{% url 'yimi_admin:questions_list' %}">在线咨询</a></li>
                            </ul>
                        </li>                          
                    </ul>
                    <!-- /main navigation -->
                </div>
            </div>
        </div>
        <!-- /sidebar -->
        <!-- Content -->
        {% block right_div %}
        {% endblock %}
        <!-- /content -->
    </div>

</body>
<script>
$(".top-menu").hover(
  function () {
    $("#sh_logout").css('display','block');
  },
  function () {
   $("#sh_logout").css('display','none');
  }
); 
</script>
</html>

templates/yimi_admin/login.html
<html lang="zh-CN" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
<meta content="noindex,nofollow" name="robots">
<link href="/static/myadmin/css/login.css" rel="stylesheet" type="text/css" />
<title>亿米传媒业务管理后台</title>
</head>
    <body class="login login-action-login wp-core-ui" >
      <div id="login" >
          <h1 align="center">亿米传媒业务管理后台</h1>
          <form method="post" action="{% url 'yimi_admin:login' %}" id="loginform" name="loginform">{% csrf_token %}
            <p>
                <label for="user_login">用户名<br>
                <input type="text" size="20" class="input" id="user_login" name="username"></label>
            </p>
            <p>
              <label for="user_pass">密码<br>
              <input type="password" size="20" value="" class="input" id="user_pass" name="password"></label>
            </p>
            <p class="submit">
              <input type="hidden" value={{next|default:''}} name="next" />
              <input type="submit" value="submit" class="btn button-primary button-large" id="wp-submit" name="wp-submit">
            </p>
          </form>
      </div>   
    </body>
</html>

templates/yimi_admin/menu_editor.html
{% extends "yimi_admin/base.html" %}
{% block right_div %}
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />

<div id="content" class="span10">
    <div class="wrapper">
        <div class="widget">
            <div class="navbar">
                <div class="navbar-inner">
                    <h6>{% if not menu_id %}新增一级菜单{% else %}修改一级菜单：{{menu.name}}{% endif %}</h6>
    
                </div>
            </div>
            <!-- /options bar -->    
            <div class="table-overflow">



<table class="mainTable">
      
      <tr>
        <td class="txtRight">名称：</td>
        <td><input id="menu-name" type="text" class="inputTxt w240" name="name" value={{menu.name|default:"默认名称"}} />
        <input type="button" value="保存修改名称" id="change-menu-name" class="inputTxt w240" /></td>
      </tr>
      <tr>
        <td class="txtRight">事件：</td>
        <td>
             <select id="type-select" class="inputTxt w240" >
                 <option>选择菜单事件类型</option>
                 <option value="click">关键字回复</option>
                 <option value="view">跳转链接</option>
                 <option value="sub_button">增加二级菜单</option>
             </select>
      </tr>
      <tr id="view-event" {% if menu.type != 'view' %} style="display:none" {% endif %} >
        <td class="txtRight">链接地址</td>
        <td>
            <form id="menu-url-form" method="post" action="{% url 'yimi_admin:menu_url' %}">{% csrf_token %}
            <input type="text" name="url" id="url-value" value="{{menu.url|default:''}}"  class="inputTxt w240"/>
            <input type="hidden" name="menuid" value="{{menu.id}}" />
            <input type="hidden" name="name" id="menu-name-url" />
            <input type="submit" name="提交"  class="inputTxt w240"/>
            </form>
        </td>
      </tr>
      
</table>


{% if message %}
<table  class="sh_table">
<tr>
    <td>{{message.keyword}}<td>
    <td>{% if message.retype == 'text' %}
        {{message.get_resource.content}}
        {% elif message.retype == 'news' %}
            {% for article in message.get_resource.articles.all %}
            <div>
                <p>{{article.title}}</p>
                <p><img src="{{article.get_image_url}}" width=100 height=100></p>
            </div>
            {% endfor %}
        {% endif %}
    </td>
</tr>
</table>
{% endif %}

<table class="sh_table">
{% for sub_menu in sub_menus %}
    <tr>
        <td>{{sub_menu.name}}</td>
    {% if sub_menu.type == 'view' %}
    <td>{{sub_menu.url}}</td>
    {% elif sub_menu.type == 'click' %}
    <td>{{sub_menu.get_message.keyword}}</td>
    {% endif %}
    <td><a href="{% url 'yimi_admin:sub_menu_update' %}?submenuid={{sub_menu.id}}&menuid={{menu.id}}">编辑<a></td>
    <td><a href="{% url 'yimi_admin:menu_delete' %}?menuid={{sub_menu.id}}&type=submenu">删除<a></td>
    </tr>
{% endfor %}
</table>


<div id="click-event" style="display:none" >

            <div class="navbar">
                <div class="navbar-inner">
                    <h6>关键字列表</h6>
    
                </div>
            </div>


                <table class="table table-striped table-bordered table-checks media-table">
                    <thead>
                        <tr>
                            <th><input type="checkbox" name="checkRow" class="styled all-select" style="width:16px"/></th>
                            <th>关键字</th>
                            <th>素材</th>
                            <th class="actions-column">操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message in messages %}
                        <tr>
                            <th><input type="checkbox" name="artwork_ids[]" class="styled" style="width:16px"  /></th>

                           <td>{{message.keyword}}</td>
                           <td>

                              {% if message.retype == 'text' %}
                              {{message.get_resource.content}}
                              {% elif message.retype == 'news' %}
                                  {% for article in message.get_resource.articles.all %}
                                  <div>
                                      <p>{{article.title}}</p>
                                  </div>
                                  {% endfor %}
                              {% endif %}
                            </td>
                           <td>
                            <input type="button" class="message-submit" value="选择" href-value="{% url 'yimi_admin:menu_click' %}?messageid={{message.id}}&type=menu&menuid={{menu.id}}"/>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>


</div>




<script type="text/javascript">
$("#type-select").change(
    function(){
        if($(this).val()=="click"){
            $("#click-event").show();
            $("#view-event").hide();
            $("#subbutton-event").hide();
	   $("#change-menu-name").hide();
        }else if($(this).val()=="view"){
            $("#click-event").hide();
            $("#view-event").show();
            $("#subbutton-event").hide();
	   $("#change-menu-name").hide();
        }else if($(this).val()=="sub_button"){
            $("#click-event").hide();
            $("#view-event").hide();
            location.href="{% url 'yimi_admin:sub_menu_add' %}?menuid={{menu.id}}&name="+$("#menu-name").val();
        }
    }
)

$("#change-menu-name").click(
    function(){
        location.href = "{% url 'yimi_admin:menu_change_name' %}?menuid={{menu.id}}&tag=menu&name="+$("#menu-name").val()
}
)

$('.message-submit').click(
    function(){
       location.href = $(this).attr("href-value")+"&name="+$("#menu-name").val();
}
)
$("#menu-url-form").submit(
    function(){
        $("#menu-name-url").val($("#menu-name").val());
}
)

</script>


            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" href="/static/myadmin/css/list.css" />


{% endblock %}