apps/nanjing/urls.py
from django.conf.urls import patterns, include, url 

import views

urlpatterns = patterns('',
    url(r'^(\w+)/articles-list/(\d+)/$', views.articles_list, name='articles_list'),
    url(r'^(\w+)/article-detail/(\d+)/$', views.article_detail, name='article_detail'),
    url(r'^(\w+)/open-account/$', views.open_account, name='open_account'),
    url(r'^(\w+)/sim-account/$', views.sim_account, name='sim_account'),
    url(r'^(\w+)/activity-user/(\d+)/$', views.activity_user, name='activity_user'),
    url(r'^(\w+)/commit-success/$', views.commit_success, name='commit_success'),
    url(r'^(\w+)/activity-list/$', views.activity_list, name='activity_list'),
    url(r'^(\w+)/show_question/$', views.show_question, name='show_question'),
)

blog/urls.py
#coding:utf8
from django.conf.urls import patterns, include, url 

import myadmin

urlpatterns = patterns('',
    url(r'^$', myadmin.news_list, name='news_list'),
    url(r'^category-list/$', myadmin.category_list, name='category_list'),
    url(r'^news-add/$', myadmin.news_add, name='news_add'),  #news意义已失效，但仍有。此处是添加,修改文章
    url(r'^article-detail/(\d+)/$', myadmin.article_detail, name='article_detail'),
    url(r'^articles-list/$', myadmin.articles_list, name='articles_list'),
    #url(r'^article-update/$', myadmin.article_update, name='article_update'),
    url(r'^article-delete/(\d+)/$', myadmin.article_delete, name='article_delete'),
    url(r'^login/$', myadmin.mylogin, name='login'),
    url(r'^logout/$', myadmin.mylogout, name='logout'),

    url(r'^reply/$', myadmin.reply, name='reply'),  #关注回复，无匹配回复, 关键字编辑
    url(r'^message-update/$', myadmin.message_update, name='message_update'),  #message的所有修改
    url(r'^keyword-reply/$', myadmin.keyword_reply, name='keyword_reply'),
    url(r'^users-list/$', myadmin.users_list, name='users_list'),
    url(r'^groups-list/$', myadmin.groups_list, name='groups_list'),
    url(r'^groups-delete/$', myadmin.groups_delete, name='groups_delete'),
    url(r'^group-name-update/$', myadmin.group_name_update, name='group_name_update'),
    url(r'^category-delete/$', myadmin.category_delete, name='category_delete'),
    url(r'^category-name-update/$', myadmin.category_name_update, name='category_name_update'),
    url(r'^category-add/$', myadmin.category_add, name='category_add'),
    url(r'^category-remove/$', myadmin.category_remove, name='category_remove'),

    url(r'^menus-list/$', myadmin.menus_list, name='menus_list'),
    url(r'^send-create-menu/$', myadmin.send_create_menu, name='send_create_menu'),
    url(r'^menu-add/$', myadmin.menu_add, name='menu_add'),
    url(r'^menu-update/$', myadmin.menu_update, name='menu_update'),
    url(r'^menu-click/$', myadmin.menu_click, name='menu_click'),
    url(r'^menu-url/$', myadmin.menu_url, name='menu_url'),
    url(r'^menu-delete/$', myadmin.menu_delete, name='menu_delete'),
    url(r'^menu-change-name/$', myadmin.menu_change_name, name='menu_change_name'),
    url(r'^sub-menu-update/$', myadmin.sub_menu_update, name='sub_menu_update'),
    url(r'^sub-menu-add/$', myadmin.sub_menu_add, name='sub_menu_add'),

    url(r'^text-update/$', myadmin.text_update, name='text_update'),
    url(r'^news-update/$', myadmin.news_update, name='news_update'),
   # url(r'^keyword-update/(\d+)/$', myadmin.keyword_update, name='keyword_update'),
    url(r'^keyword-add/$', myadmin.keyword_add, name='keyword_add'),
    url(r'^keyword-delete/$', myadmin.keyword_delete, name='keyword_delete'),
    url(r'^groups-add/$', myadmin.groups_add, name='groups_add'),
    url(r'^group-update/$', myadmin.group_update, name='group_update'),
    url(r'^group-remove/$', myadmin.group_remove, name='group_remove'),

    url(r'^activity-list/$', myadmin.activity_list, name='activity_list'),
    url(r'^open-account-list/$', myadmin.open_account_list, name='open_account_list'),
    url(r'^sim-account-list/$', myadmin.sim_account_list, name='sim_account_list'),


    url(r'^account-delete/(\w+)/(\d+)/$', myadmin.account_delete, name='account_delete'),
    url(r'^activity-add/$', myadmin.activity_add, name='activity_add'),
    url(r'^activity-delete/(\d+)/$', myadmin.activity_delete, name='activity_delete'),
    url(r'^activity-account-list/(\d+)/$', myadmin.activity_account_list, name='activity_account_list'),
    url(r'^activity-status/(\d+)/$', myadmin.activity_status, name='activity_status'),


    url(r'^questions-list/$', myadmin.questions_list, name='questions_list'),  #客服列表
    url(r'^answer-question/$', myadmin.answer_question, name='answer_question'),  #客服列表
    url(r'^kefu-delete/$', myadmin.kefu_delete, name='kefu_delete'),  #客服列表

)

yimi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from yimi.settings import TOKEN
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^%s/(\d+)/$'%TOKEN, 'blog.views.weixin_api', name='weixin_api'),
    url(r'^$', 'blog.views.message', name='message'),
    url(r'^yimi-admin/', include('blog.urls', namespace="yimi_admin")),
    url(r'^a/', include('apps.nanjing.urls', namespace="nanjing")), #appitem slug

    url(r'^myueditor/upload/$', 'myueditor.views.upload', name='upload'),
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/nanjing/models.py
#coding:utf8

from django.db import models
from blog.utils import upload_file_handler
from blog.models import Article, AppItem
from django.contrib.auth.models import User

class OpenAccount(models.Model):
    appitem = models.ForeignKey(AppItem, verbose_name='应用', blank=True, null=True)
    name = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="姓名")      
    cid = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="身份证号")      
    tel = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="电话")      
    images = models.ManyToManyField(
        "ImageItem", null=True, blank=True, verbose_name="图片")
    lbs = models.CharField(
        max_length=256, blank=True, verbose_name="位置")
    openid = models.CharField(
        max_length=256, blank=True, verbose_name="openid")
    create_time = models.DateTimeField(auto_now_add=True,  blank=True, null=True,verbose_name='创建时间')
    
class ImageItem(models.Model):
    name = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="状态")      
    image = models.ImageField(
        max_length=128, upload_to=upload_file_handler, verbose_name="图片")


class SimAccount(models.Model):
    appitem = models.ForeignKey(AppItem, verbose_name='应用', blank=True, null=True)
    name = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="姓名")      
    cid = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="身份证号")      
    tel = models.CharField(
        max_length=128, blank=True,null=True,verbose_name="电话")      
    lbs = models.CharField(
        max_length=256, blank=True, verbose_name="位置")
    bank = models.CharField(
        max_length=256, blank=True, verbose_name="开户银行")
    openid = models.CharField(
        max_length=256, blank=True, verbose_name="openid")
    create_time = models.DateTimeField(auto_now_add=True,  blank=True, null=True, verbose_name='创建时间')

#class Activity(models.Model):
#    title = models.CharField(
#        max_length=512, blank=True,null=True,verbose_name="名称")      
#    a_time = models.CharField(
#        max_length=256, blank=True,null=True,verbose_name="时间")      
#    count = models.IntegerField(verbose_name="人数", blank=True, null=True)
#    appitem = models.ForeignKey(AppItem, verbose_name='应用', blank=True, null=True)
#    activity_users = models.ManyToManyField('ActivityUser', verbose_name='参与人', blank=True, null=True)
#
#class ActivityUser(models.Model):
#    name = models.CharField(
#        max_length=128, blank=True,null=True,verbose_name="姓名")      
#    cid = models.CharField(
#        max_length=128, blank=True,null=True,verbose_name="身份证号")      
#    tel = models.CharField(
#        max_length=128, blank=True,null=True,verbose_name="姓名")      
#    lbs = models.CharField(
#        max_length=256,  blank=True, verbose_name="位置")
#    openid = models.CharField(
#        max_length=256, blank=True, verbose_name="openid")
#    create_time = models.DateTimeField(auto_now_add=True,  blank=True, null=True,verbose_name='创建时间')

apps/nanjing/views.py
#coding:utf8
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

from blog.models import *
from blog.utils import get_user_openid
from blog.utils import get_entry_page, page_turning
from models import *

def get_appitem(slug):
    appitem = AppItem.objects.filter(slug=slug).first()
    return appitem



def article_detail(request, slug, id):
    appitem = get_appitem(slug)
    article = Article.objects.filter(id=id).first()
    if not article:
        raise Http404
    context = { 
        'article': article,
        'appitem': appitem,
    }   
    return render_to_response('nanjing/article_detail.html', context,
        context_instance=RequestContext(request))

def articles_list(request, slug, id):
   # category = Category.objects.filter(id=id, status=True).first()
   # appitem = category.appitem_set.first()
    appitem = get_appitem(slug)
    code = request.GET.get("code", '')
   # openid = get_user_openid(appitem.appid, appitem.app_secret, code)
    openid = appitem.get_user_openid(request)
    category = appitem.categories.get(id=id)        
    if openid and code:
        user = AppUser.objects.get(openid=openid)
        if not category.status: #不显示的分类
            if appitem.app_groups.filter(app_users=user, status=True).exists():
                articles = category.articles.all()
            else:
                return render_to_response('nanjing/notavailable.html', {},
                    context_instance=RequestContext(request))
        else:
            articles = category.articles.all()
    elif not code:
        articles = category.articles.all()
    else:
        articles = []
            
    page = int(request.GET.get("p",1))
   # return_articles = get_entry_page(articles,10,page)
    matchs, show_pages = page_turning(articles, request, 4)
    context = { 
        'appitem': appitem,
        'articles': articles,
        'matchs': matchs,
    }   
    return render_to_response('nanjing/articles_list.html', context,
        context_instance=RequestContext(request))

def reverse_url(slug):
    return reverse("nanjing:commit_success", args=(slug,))

def open_account(request, slug):
    appitem = get_appitem(slug)
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
        openaccount = appitem.openaccount_set.filter(cid=cid).first()
        if not openaccount:
            appitem.openaccount_set.create(name=name, cid=cid, tel=tel)
            return HttpResponseRedirect(reverse_url(slug))
    context = {'appitem': appitem}
    
    return render_to_response('nanjing/open_account_form.html', context,
        context_instance=RequestContext(request))

def sim_account(request, slug):
    appitem = get_appitem(slug)
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
        bank = request.POST.get('bank')
        simaccount = appitem.simaccount_set.filter(cid=cid).first()
        if not simaccount:
            appitem.simaccount_set.create(name=name, cid=cid, tel=tel, bank=bank)
            return HttpResponseRedirect(reverse_url(slug))
    context = {'appitem': appitem}
    
    return render_to_response('nanjing/sim_account_form.html', context,
        context_instance=RequestContext(request))

def activity_user(request, slug, cid):
    appitem = get_appitem(slug)
    activity = appitem.activity_set.filter(id=cid).first()
    if request.method == "POST":
        name = request.POST.get('name')
        cid = request.POST.get('cid')
        tel = request.POST.get('tel')
       # openid = request.POST.get("openid")
       # if openid and activity.activity_users.filter(openid=openid).exists():
        activity.activity_users.create(name=name, cid=cid, tel=tel)
        return HttpResponseRedirect(reverse_url(slug))
    context = {'appitem': appitem, 'activity': activity}
    
    return render_to_response('nanjing/activity_user_form.html', context,
        context_instance=RequestContext(request))

def commit_success(request, slug):
    return render_to_response('nanjing/commit_success.html', {},
        context_instance=RequestContext(request))
def activity_list(request, slug):
    appitem = get_appitem(slug)
    activities = appitem.activity_set.filter(status=True)
    matchs, show_pages = page_turning(activities, request, 1)
    context = {'appitem': appitem, 'activities': activities, 'matchs': matchs}
    
    return render_to_response('nanjing/activity_list.html', context,
        context_instance=RequestContext(request))

def show_question(request, slug):
    '''客户服务'''
    appitem = get_appitem(slug)
    if request.method == 'POST':
        openid = request.POST.get('openid')
        question = request.POST.get('question')
        if openid:
            user = AppUser.objects.filter(openid=openid).first()
            if not user:
                user = AppUser.objects.create(openid=openid)
            KeFu.objects.create(appitem=appitem, appuser=user, question=question)
            return HttpResponseRedirect(reverse_url(slug))

    openid = appitem.get_user_openid(request)
    kefus = None
    if openid:
        user = AppUser.objects.filter(openid=openid).first()
        if not user:
            user = AppUser.objects.create(openid=openid)
        kefus = KeFu.objects.filter(appitem=appitem, appuser=user)
    context = {
        'kefus': kefus,
        'openid': openid,
        'appitem': appitem,
    }
    return render_to_response('nanjing/show_question.html', context,
        context_instance=RequestContext(request))

templates/nanjing/activity_list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{{appitem.name}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body>
	<div class="wrap">
	    {% for activity in matchs %}
    	<dl class="list_box" style="padding:30px;">
        	<dt style="font-size:40px;">{{activity.title}}</dt>
           {% if activity.a_time %} <dd><b>时间：</b>{{activity.a_time}}</dd> {% endif %}
           {% if activity.xingshi %} <dd><b>形式：</b>{{activity.xingshi}}</dd> {% endif %}
           {% if activity.place %} <dd><b>地点：</b>{{activity.place}}</dd> {% endif %}
           {% if activity.speaker %} <dd><b>主讲：</b>{{activity.speaker}}</dd> {% endif %}
          {% if activity.count %}  <dd><b>人数：</b>{{activity.count}}</dd> {% endif %}
           {% if activity.content %} <dd><b>内容：</b>{{activity.content|safe}}</dd> {% endif %}
            <dd style="height:30px;"><button style="float:right;width:100px;height:45px;"
 onclick="window.location.href='http://{{appitem.domain}}{% url 'nanjing:activity_user' appitem.slug activity.id %}'">报名</button></dd>
        </dl>
        {% endfor %}
    </div>
    <div class="tools">
    	<a href="{% if matchs.has_previous %}?p={{matchs.previous_page_number }}{% endif %}" class="left">上一页</a>
        <a href="{% if matchs.has_next %}?p={{matchs.next_page_number}}{% endif %}" class="right click">下一页</a>
    </div>
</body>
</html>

templates/nanjing/activity_user_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />

<title>{{activity.title}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body >
	<div class="formWrap">
	    <form action="{% url 'nanjing:activity_user' appitem.slug activity.id %}" method="post">{%csrf_token%}
    	<ul class="formList">
        	<li class="title">参加活动报名：</li>
            <li><input name="name" type="text"  class="inputTxt" placeholder="姓名"/></li>
            <li><input name="cid" type="text"  class="inputTxt" placeholder="身份证号"/></li>
            <li><input name="tel" type="text"  class="inputTxt" placeholder="手机号"/></li>
            <li><input name="" type="submit" class="inputBut" placeholder="提交" /></li>
        </ul>
        </form>
    </div>
    
</body>
</html>

templates/nanjing/article_detail.html
<!doctype html>
<html lang="cn">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="initial-scale=1.0,user-scalable=no"/>
<title>{{appitem.name}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" />
</head>

<body class="detailedCon">
<!--标题-->
<h1 class="contitle">{{article.title}}</h1>

<!--时间 作者 来源-->
<div><span class="article_detail_date">{{article.create_time|date:'Y-n-d'}}</span>&nbsp;<span class="article_detail_author"><a href="#">{{article.author}}</a></span></div>

<!--内容-->  
<section>{{article.content|safe}} </section>
<p><br /></p>
{% if article.url %}
<p><a href="{{article.url}}">阅读原文>></a></p>
{% endif %}
</body>
</html>

templates/nanjing/articles_list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{{appitem.name}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body>
	<div class="wrap">
	    {% for article in matchs %}
    	<dl class="list_box clx">
        	<div class="listimg"><img src="{{article.get_image_url}}" height="180px"/></div>
        	<dt><a href="{{article.get_url}}" class="articles_list_title">{{article.title}}</a></dt>
            <dd><a href="{{article.get_url}}" class="articles_list_dscrip">{{article.get_description|safe}}</a></dd>
        </dl>
        {% endfor %}
    </div>
    <div class="tools">
    	<a href="{% if matchs.has_previous %}?p={{matchs.previous_page_number }}{% endif %}" class="left">上一页</a>
        <a href="{% if matchs.has_next %}?p={{matchs.next_page_number}}{% endif %}" class="right click">下一页</a>
    </div>
</body>
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
<script src="/static/nanjing/js/base.js"></script>
</html>

templates/nanjing/commit_success.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{{appitem.name}}</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body >
	<div class="formWrap">
    	<div class="cgBox">提交成功</div>
        
    </div>
    
</body>
</html>

templates/nanjing/form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
</head>

<body >
	<div class="formWrap">
	    <form action="{% url 'nanjing:open_account' appitem.slug %}" method="post">{%csrf_token%}
    	<ul class="formList">
        	<li class="title">预约开户：</li>
            <li><input name="name" type="text"  class="inputTxt" value="姓名"/></li>
            <li><input name="cid" type="text"  class="inputTxt" value="身份证号"/></li>
            <li><input name="tel" type="text"  class="inputTxt" value="手机号"/></li>
            <li><input name="" type="submit" class="inputBut" value="下一步" /></li>
        </ul>
        </form>
    </div>
    
</body>
</html>

templates/nanjing/open_account_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>申请模拟账号</title>
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
<link href="/static/watch/css/change.css" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />
</head>

<body >
	<div class="formWrap">
	    <form action="{% url 'nanjing:open_account' appitem.slug %}" method="post">{%csrf_token%}
    	<ul class="formList">
        	<li class="title">预约开户：</li>
            <li><input name="name" type="text"  class="inputTxt" placeholder="姓名"/></li>
            <li><input name="cid" type="text"  class="inputTxt" placeholder="身份证号"/></li>
            <li><input name="tel" type="text"  class="inputTxt" placeholder="手机号"/></li>
            <li><input name="" type="submit" class="inputBut" value="提交" /></li>
        </ul>
        </form>
    </div>
        <script>
	$(function(){
		$(".inputBut").click(function(){
			$("input").each(function(){
				if($(this).val()==''){
			alert('请完整输入信息');
			return false;
			}	
			});
		});
});
       </script>
</body>
</html>

templates/nanjing/show_question.html
<!doctype html>
<html>
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
	<title>客服</title>
	<style>
	*{
		font-family:'Microsoft Yahei';
		background-color:#eee;
	}
	textarea{
		width:100%;
		height:90%;
		border:1px solid #D6D6D6;
		background-color: white;
	}
	h1{
		font-size:3em;
		font-weight: normal;
	}

	h2{
		font-size:1em;
		background-color: white;
		font-weight: normal;

	}

	button{
		float:right;
		width:100px;
		height:35px;
		background-color:#f90;
		border:none;
		color:white;
		border-radius: 3px;
	}

	.yhd{
		border:1px solid #dbdbdd;
		margin-top:10px;
		margin-bottom:20px;
		background-color: white;
		padding:5px;
	}

	.yhd_item{
		min-height:30px;
		width:100%;
		border:1px solid #D6D6D6;
		margin-bottom: 5px;
	}
</style>
</head>
<body>
	<h1>在线咨询</h1>
	<hr>
	<section class="yhd">
		<h2>已回答问题</h2>
		<div class="yhd_item">
            {% for kefu in kefus %}
			<h3>{{kefu.question}} 提问时间:{{kefu.create_time|date:'Y-m-d H:i'}}</h3>
            
			<p>{{kefu.answer|default:"未回答"}}  {% if kefu.answer %}{{kefu.answer_time|date:'Y-m-d H:i'}}{% endif %}</p>
            {% endfor %}
		</div>
		<div class="yhd_item"></div>
	</section>
    <form action='{% url 'nanjing:show_question' appitem.slug %}' method='post'>{% csrf_token %}
	<textarea name="question" id="question" cols="30" rows="10" placeholder="请在此输入问题"></textarea>
    <input type="hidden" name="openid" value="{{openid}}" />
    <input type='submit' value="提交"/>
    </form>
</body>
</html>

templates/nanjing/sim_account_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="user-scalable=no" />
<title>预约开户</title>
<link href="/static/nanjing/css/base.css" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
</head>

<body >
	<div class="formWrap">
	    <form action="{% url 'nanjing:sim_account' appitem.slug %}" method="post">{%csrf_token%}
    	<ul class="formList">
        	<li class="title">预约开户：</li>
            <li><input name="name" type="text"  class="inputTxt" placeholder="姓名"/></li>
            <li><input name="cid" type="text"  class="inputTxt" placeholder="身份证号"/></li>
            <li><input name="tel" type="text"  class="inputTxt" placeholder="手机号"/></li>
            <li><input name="bank" type="text"  class="inputTxt" placeholder="开户银行"/></li>
            <li><input name="" type="submit" class="inputBut" value="提交" /></li>
        </ul>
        </form>
    </div>
            <script>
	$(function(){
		$(".inputBut").click(function(){
			$("input").each(function(){
				if($(this).val()==''){
			alert('请完整输入信息');
			return false;
			}	
			});
		});
});
       </script>
</body>
</html>